### ISSUE TITLE
wrong array name in Region.php

### ISSUE THREAD

**Issue by artwells** [tomasinchoo/Inchoo_USDisableRegions#1]
app/code/community/Inchoo/USDisableRegions/Model/Adminhtml/System/Config/Source/Region.php: 41

```
        $allowedCountries[] = array('value' => $region["name"], 'label' =>$region["name"]);
```

should be

```
        $allowedRegions[] = array('value' => $region["name"], 'label' =>$region["name"]);
```

**Comment by shashankkumrawat** [comment]
yes,,after updating this all regions are showing but I am getting all regions on checkout page in State dropdown list. How can show only enabled region here.?
